config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'articles#index'
  resources :users
  resources :articles do
    resources :comments, only: [:index, :create]
    resources :likes, only: :create
  end
  post "likes/:article_id/destroy" => "likes#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: :new
  
  def index
    @articles = Article.all
    @article = Article.new
    @like = Like.new
  end

  def create
    Article.create(article_params)
    redirect_to action: 'index'
  end

  def show
    @articles = Article.where('title LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_comments_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to action: 'index'
  end

  private

  def article_params
    params.require(:article).permit(:title, :body).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  
  def index
    @comment = Comment.new
    @comments = @article.comments
    @like = Like.new
  end

  def create
    @comment = @article.comments.create(comment_params)
    redirect_to action: 'index'
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    Like.create(user_id: current_user.id, article_id: params[:article_id])
    redirect_to articles_path
  end

  def destroy
    @like = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
    @like.destroy
    redirect_to articles_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @articles = Article.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.slim
.articles
    - @articles.each do |article|
      .article
        p.article__title 
          = article.title
        p.article__body 
          = article.body
        .article__links
          = link_to article_comments_path(article) do
            i.fa.fa-eye.article__links__show
          -if user_signed_in?
            -if Like.find_by(user_id: current_user.id, article_id: article.id)
              = link_to "likes/#{article.id}/destroy", method: :post do
                i.fa.fa-heart.article__links__like.un_like
            -else
              = link_to article_likes_path(article), method: :post do
                i.fa.fa-heart.article__links__like.like
            = article.likes.count
          = link_to article_path(article), method: :delete do
            i.fa.fa-trash.article__links__delete
= render "layouts/footer"

app/views/articles/show.html.slim
.serch
  input#serch-form
  #serch-title
    p.serch-title title
  #serch-result

app/views/comments/index.html.slim
.articles
  = render "layouts/article", article: @article
  .comments
    p.comments_border Comments
    - @comments.each do |c|
      .comment
        p.comment_message
          = c.message
-if user_signed_in?
  = render 'layouts/btn'
  = render 'layouts/footer'

app/views/layouts/_article.html.slim
.article
  p.article__title 
    = article.title
  p.article__body 
    = article.body
  .article__links
    = link_to article_comments_path(article) do
      i.fa.fa-eye.article__links__show
    -if user_signed_in?
      -if Like.find_by(user_id: current_user.id, article_id: article.id)
        = link_to "likes/#{article.id}/destroy", method: :post do
          i.fa.fa-heart.article__links__like.un_like
      -else
        = link_to article_likes_path(article), method: :post do
          i.fa.fa-heart.article__links__like.like
      = article.likes.count
    = link_to article_path(article), method: :delete do
      i.fa.fa-trash.article__links__delete

app/views/layouts/_btn.html.slim
.btn2
  a.js-modal-open.btn-social-circle.btn-social-circle--twitter href="#" data-target="modal02"
    i.fa.fa-edit
#modal02.modal.js-modal
  .modal__bg.js-modal-close
  .modal__content
    .form
      = form_with model: [@article, @comment], local: true do |f|
        .msr_text_01
          = f.label :message
          = f.text_field :message, placeholder: 'message:'
        .msr_sendbtn_05
          = f.submit class: "form-btn"

app/views/layouts/_footer.html.slim
footer
  -if user_signed_in?
    .btn
      a.js-modal-open.btn-social-circle.btn-social-circle--twitter href="#" data-target="modal01"
        -if @article.id.blank?
          i.fa.fa-edit
        -else
          i.fa.fa-undo
  #modal01.modal.js-modal
    .modal__bg.js-modal-close
    .modal__content
      .form
        = form_with model: @article, local: true do |f|
          .msr_text_01
            = f.label :title
            = f.text_field :title, placeholder: 'title:'
          .msr_textarea_05
            = f.label :body, value: "text"
            = f.text_area :body, placeholder: 'text:'
          .msr_sendbtn_05
            = f.submit class: "form-btn"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MyBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    header
      .title my-blog
      .navbar
        ul.menu-list
          li.menu-list_home
            = link_to articles_path, turbolinks: false do
              i.fa.fa-home
          - if user_signed_in?
            li.menu-list_serch
              = link_to "articles/serch" do
                i.fa.fa-search
            li.menu-list_user-name 
              = link_to "#{current_user.name}", user_path(current_user)
            li.menu-list_logout 
              = link_to destroy_user_session_path, method: :delete do
                i.fa.fa-share
          - else
            li.menu-list_login 
              = link_to new_user_session_path do
                i.fa.fa-unlock
            li.menu-list_sign_in
              = link_to new_user_registration_path do
                i.fa.fa-user-plus
    .main-content
      = yield

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br

app/views/users/show.html.slim
.articles
  - @articles.each do |article|
    .article
      p.article__title 
        = article.title
      p.article__body 
        = article.body
      .article__links
        = link_to article_comments_path(article) do
          i.fa.fa-eye.article__links__show
        -if user_signed_in?
          -if Like.find_by(user_id: current_user.id, article_id: article.id)
            = link_to "likes/#{article.id}/destroy", method: :post do
              i.fa.fa-heart.article__links__like.un_like
          -else
            = link_to article_likes_path(article), method: :post do
              i.fa.fa-heart.article__links__like.like
        = article.likes.count
        = link_to article_path(article), method: :delete do
          i.fa.fa-trash.article__links__delete